### ISSUE TITLE
Missing Azure pipelines expressions

### ISSUE THREAD

**Issue by premun** [sharpliner/sharpliner#141]
### Context
Currently, we can do expressions such as `or()`, `eq()` and few more, but not all.

### Goals
- [x] We need to implement all expressions such as `containsValue` - [[full list]](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) (#147)
- [x] We need to have some way to allow user specify any string expression in case there is some edge case we forget about (#146)
- [x] All of the current experssions must accept `string` parameters because we need to be able to assemble any expression (#144)
- [x] Make `or` and `and` accept various number of parameters (#144)
