### ISSUE TITLE
Document all public API's - Remove CS1591 NoWarn

### ISSUE THREAD

**Issue by Meir017** [sharpliner/sharpliner#325]
All public API's should be documented :)

[build.log](https://github.com/user-attachments/files/17535441/build.log)

- [x] YamlStringEnumConverter - made internal
- [x] MultilineStringEmitter - should this be internal?
- [x] IDependsOn - pubic API 
- [x] SharplinerSerializer - made internal
- [x] TargetPathType
- [x] SharplinerConfiguration
- [x] TaskBuilderBase
- [x] VariablesReference #326
- [x] TemplateDefinitionCollection, TemplateDefinition, Template
- [x] PublicDefinitions
- [x] Pipeline, PipelineDefinition, PipelineDefinitionCollection
- [x] Parameter
- [x] VariableDefinition
- [x] Conditioned #334
- [x] ValidationsExtensions - public API
- [x] ISharplinerDefinitionCollection
- [x] IDefinitionValidation

tasks:
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\AzureDevOpsTask - #352
- [x] src/Sharpliner/AzureDevOps/Model/Tasks/Builders/ScriptTaskBuilder.cs - #350 
- [x] src/Sharpliner/AzureDevOps/Model/Tasks/ScriptTask.cs - #350 
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\BashTask - #358 
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Builders\BashTaskBuilder - #358
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Builders\CheckoutTaskBuilder - #357 
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\CheckoutTask - #357 
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\DownloadTask - #359
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Builders\DownloadTaskBuilder - #359
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Builders\PowerShellTaskBuilder - #360
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Builders\PwshTaskBuilder - #360
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\PowerShellTask - #360
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\ArchiveFilesTask - #362
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\CopyFilesTask - #362
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DeleteFilesTask - #362
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\PublishCodeCoverageResultsTask - #362
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\PublishTestResultsTask - #362
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Builders\DotNetTaskBuilder - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetBuildCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetPackCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetPublishCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetPushCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetRestoreCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\DotNetTestCoreCliTask - #364
- [x] src\Sharpliner\AzureDevOps\Model\Tasks\Marketplace\UseDotNetTask - #364
- [ ] src\Sharpliner\AzureDevOps\Model\Tasks\PublishTask - #365 

~625 total warnings

**Comment by premun** [comment]
Phew.. Can copilot somehow help with that? 😅

**Comment by Meir017** [comment]
@premun Definitely! although in some cases it doesn't quite do the job right, but it really simplifies this

**Comment by premun** [comment]
Since these will technically be breaking changes when making things internal, I'd wait with a new version of the package and bump the minor (so I believe `1.6.x`)

**Comment by Meir017** [comment]
down to 264 warnings

**Comment by Meir017** [comment]
@premun should [`ValidationsExtensions.cs`](https://github.com/sharpliner/sharpliner/blob/main/src/Sharpliner/AzureDevOps/Validation/ValidationsExtensions.cs) be public? I think it's used internally only

**Comment by premun** [comment]
@Meir017 I think the idea is that if you want to write your own pipeline validation, these are handy utilities which can give you things like list of jobs etc

**Comment by premun** [comment]
I think `IDependsOn` could stay public, it might also be useful for some custom validations, I imagine
